spring:
#  sql:
#    init:
#      mode: always
#      schema-locations:
#        - classpath:schema.sql
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  datasource:
#    url: jdbc:mysql://localhost:3306/BOARD_00?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/BOARD_00
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234!!